apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
      - name: report-storage
        mountPath: /reports
  volumes:
    - name: report-storage
      persistentVolumeClaim:
        claimName: trivy-report-pvc
